### ISSUE TITLE
no tags in github repo

### ISSUE THREAD

**Issue by gdt** [salva/p5-Net-SFTP-Foreign#14]
I expect to find tags in the github repo corresponding to releases on CPAN, as part of understanding changes for updating the pkgsrc entry.  This is not a big deal, but it would be nice.

**Comment by salva** [comment]
Hi,

You can use metacpan for comparing different versions of a Perl module.

For instance: https://metacpan.org/release/SALVA/Net-SFTP-Foreign-1.93/diff/SALVA%2FNet-SFTP-Foreign-1.92_03/lib/Net/SFTP/Foreign.pm

**Comment by gdt** [comment]
Thanks.   I've left a note in the package entry with the metacpan pointer.
 
(It still seems like a bug not to have tags, in terms of tracking the journey from repo to CPAN to user.)
